{
    'name': 'SN WSD Print',
    'version': '19.0.1.2.0',
    'summary': 'ZPL printing for WSD serial and material labels',
    'depends': ['sn_wsd_mrp', 'sn_wsd_barcode', 'purchase'],
    'data': [
        'data/material_serial_sequence.xml',
        'security/ir.model.access.csv',
        'wizard/internal_serial_generate_print_wizard_views.xml',
        'wizard/incoming_material_label_wizard_views.xml',
        'report/internal_serial_label_templates.xml',
        'report/internal_serial_label_reports.xml',
        'report/incoming_material_label_templates.xml',
        'report/incoming_material_label_reports.xml',
        'views/mes_order_views.xml',
        'views/internal_serial_views.xml',
        'views/stock_picking_views.xml',
    ],
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
