{
    'name': 'SN WSD Maintenance',
    'version': '19.0.1.1.0',
    'summary': 'Equipment plans, inspections, downtime, and MES maintenance integration',
    'depends': ['maintenance', 'mrp', 'sn_wsd_mrp'],
    'data': [
        'security/maintenance_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/maintenance_cron.xml',
        'views/maintenance_plan_views.xml',
        'views/maintenance_execution_views.xml',
        'views/maintenance_downtime_views.xml',
        'views/maintenance_equipment_views.xml',
        'views/maintenance_request_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
