{
    'name': 'SN WSD Report',
    'version': '19.0.3.1.1',
    'summary': 'Reporting extensions for SN WSD manufacturing',
    'depends': ['sn_wsd_api', 'sn_wsd_quality'],
    'data': [
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'wizard/workorder_terminal_wizard_views.xml',
        'wizard/workorder_report_correction_wizard_views.xml',
        'wizard/meter_workorder_scan_wizard_views.xml',
        'views/mrp_workorder_report_bridge_views.xml',
        'views/workorder_report_views.xml',
        'views/mes_analysis_report_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            ('include', 'web.chartjs_lib'),
            'sn_wsd_report/static/src/js/terminal_client_action.js',
            'sn_wsd_report/static/src/xml/terminal_client_action.xml',
            'sn_wsd_report/static/src/scss/workorder_terminal.scss',
            'sn_wsd_report/static/src/scss/terminal_client_action.scss',
            'sn_wsd_report/static/src/js/mes_big_screen_action.js',
            'sn_wsd_report/static/src/xml/mes_big_screen_action.xml',
            'sn_wsd_report/static/src/scss/mes_big_screen_action.scss',
        ],
    },
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
