{
    'name': 'SN WSD Exception Management',
    'version': '19.0.4.1.0',
    'summary': 'MES exception tickets: terminal reporting, category routing, claim, suspension, closure confirmation, Pareto',
    'depends': ['mail', 'sn_wsd_mrp'],
    'data': [
        'security/exception_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/exception_team_data.xml',
        'data/exception_category_data.xml',
        'data/exception_cron.xml',
        'views/exception_team_views.xml',
        'views/exception_category_views.xml',
        'views/exception_reason_views.xml',
        'views/exception_ticket_views.xml',
        'views/exception_wizard_views.xml',
        'reports/exception_report_templates.xml',
        'reports/exception_report_actions.xml',
        'views/menu_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sn_wsd_exception/static/src/js/pareto_dashboard.js',
            'sn_wsd_exception/static/src/xml/pareto_dashboard.xml',
        ],
    },
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
