{
    'name': 'SN WSD Stock',
    'version': '19.0.1.1.1',
    'summary': 'Incoming material labels and internal lot generation',
    'category': 'Supply Chain/Inventory',
    'depends': ['stock', 'mail', 'resource', 'sn_wsd_mrp'],
    'data': [
        'views/stock_orderpoint_views.xml',
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'wizard/incoming_material_label_wizard_views.xml',
        'report/incoming_material_label_templates.xml',
        'report/incoming_material_label_reports.xml',
        'views/stock_lot_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_rule_views.xml',
    ],
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
