{
    'name': 'SN WSD SMT',
    'version': '19.0.3.2.1',
    'summary': 'SMT material table and online loading management',
    'depends': ['mrp', 'maintenance', 'sn_wsd_mrp', 'sn_wsd_maintenance', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/sn_smt_config_views.xml',
        'wizard/sn_smt_change_wizard_views.xml',
        'wizard/sn_smt_xl_wizard_views.xml',
        'wizard/sn_smt_zc_wizard_views.xml',
        'wizard/sn_smt_material_query_wizard_views.xml',
        'wizard/sn_smt_lcsl_wizard_views.xml',
        'wizard/sn_smt_bl_wizard_views.xml',
        'wizard/sn_smt_tp_wizard_views.xml',
        'wizard/sn_smt_table_import_wizard_views.xml',
        'views/product_views.xml',
        'views/mrp_production_views.xml',
        'views/sn_smt_views.xml',
        'views/sn_smt_pcb_panel_views.xml',
        'views/internal_serial_views.xml',
        'views/stock_lot_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
