{
    'name': "Device Management",
    'summary': "Device data collection (reflow soldering, etc.)",
    'category': 'Manufacturing/Device Management',
    'version': '19.0.1.0.0',
    'depends': ['base', 'product', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/reflow_data_views.xml',
        'views/wave_data_views.xml',
        'views/device_doc_views.xml',
        
        'views/equipment_config_views.xml',
        'views/equipment_views.xml',
        'views/maint_template_views.xml',
        'data/check_sequence.xml',
        'views/check_plan_views.xml',
        'views/check_task_views.xml',
        'views/check_log_views.xml',
        'views/check_config_views.xml',
        'data/maint_sequence.xml',
        'views/maint_plan_views.xml',
        'views/maint_task_views.xml',
        'views/maint_log_views.xml',
        'views/maint_config_views.xml',
        'data/cal_sequence.xml',
        'views/cal_plan_views.xml',
        'views/cal_task_views.xml',
        'views/cal_log_views.xml',
        'views/cal_config_views.xml',
        'data/equipment_seed.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
