{
    'name': "Device Management",
    'summary': "Device data collection (reflow soldering, etc.)",
    'category': 'Manufacturing/Device Management',
    'version': '19.0.4.0.0',
    'depends': ['base', 'product', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/company_rules.xml',
        'views/reflow_data_views.xml',
        'views/wave_data_views.xml',
        'views/device_doc_views.xml',

        'views/equipment_config_views.xml',
        'views/equipment_views.xml',
        'views/maint_template_views.xml',
        'data/check_sequence.xml',
        'views/check_plan_views.xml',
        'views/check_task_views.xml',
        'views/check_log_views.xml',
        'views/check_config_views.xml',
        'data/maint_sequence.xml',
        'views/maint_plan_views.xml',
        'views/maint_task_views.xml',
        'views/maint_log_views.xml',
        'views/maint_config_views.xml',
        'data/cal_sequence.xml',
        'views/cal_plan_views.xml',
        'views/cal_task_views.xml',
        'views/cal_log_views.xml',
        'views/cal_config_views.xml',
        'data/repair_sequence.xml',
        'views/repair_order_views.xml',
        'data/knowledge_sequence.xml',
        'views/knowledge_views.xml',
        'data/oee_sequence.xml',
        'views/oee_views.xml',
        'data/equipment_seed.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'author': 'SNCIC',
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'sn_wsd_device/static/src/scss/repair_wizard.scss',
            'sn_wsd_device/static/src/oee/oee_trend_chart/oee_trend_chart.js',
            'sn_wsd_device/static/src/oee/oee_trend_chart/oee_trend_chart.xml',
            'sn_wsd_device/static/src/oee/oee_trend_chart/oee_trend_chart.scss',
            'sn_wsd_device/static/src/oee/oee_report/oee_report_action.js',
            'sn_wsd_device/static/src/oee/oee_report/oee_report_action.xml',
            'sn_wsd_device/static/src/oee/oee_report/oee_report.scss',
        ],
    },
}
