{
    'name': 'SN WSD MRP',
    'version': '19.0.9.0.3',
    'summary': 'Manufacturing extensions built on Odoo MRP (MES orders, station flow)',
    'depends': ['product', 'mrp', 'stock', 'purchase', 'hr', 'mail', 'sn_wsd_device'],
    'data': [
        'data/stock_package_type.xml',
        'data/scrap_reason_data.xml',
        'security/mes_security.xml',
        'security/ir.model.access.csv',
        'wizard/mrp_team_member_wizard_views.xml',
        'wizard/mrp_electronics_wizard_views.xml',
        'wizard/mrp_production_split_views.xml',
        'views/res_partner_views.xml',
        'views/mrp_base_config_views.xml',
        'views/mrp_workcenter_views.xml',
        'views/process_route_drawing_views.xml',
        'views/process_route_version_views.xml',
        'views/meter_process_route_views.xml',
        'views/meter_pack_views.xml',
        'views/serial_identity_views.xml',
        'views/production_process_doc_views.xml',
        'wizard/generate_sn_wizard_views.xml',
        'views/mes_order_views.xml',
        'views/mrp_production_views.xml',
        'views/mes_route_check_views.xml',
        'views/product_views.xml',
        'views/menu_views.xml',
        'views/mrp_electronics_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            ('include', 'web.chartjs_lib'),
            'sn_wsd_mrp/static/src/scss/mrp_production.scss',
            'sn_wsd_mrp/static/src/views/fields/x2many_multi_add/x2many_multi_add_field.js',
        ],
    },
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
