{
    'name': 'SN WSD MRP',
    'version': '19.0.3.5.7',
    'summary': 'Manufacturing and internal serial extensions built on Odoo MRP',
    'depends': ['product', 'mrp', 'stock', 'maintenance', 'hr', 'mail'],
    'data': [
        'data/stock_package_type.xml',
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'wizard/mrp_team_member_wizard_views.xml',
        'wizard/mrp_electronics_wizard_views.xml',
        'wizard/mrp_production_split_views.xml',
        'views/res_partner_views.xml',
        'views/mrp_base_config_views.xml',
        'views/mrp_workcenter_views.xml',
        'views/meter_process_route_views.xml',
        'views/internal_serial_views.xml',
        'views/meter_aging_views.xml',
        'views/meter_pack_views.xml',
        'views/mrp_production_views.xml',
        'views/manufacturing_batch_views.xml',
        'views/mrp_workorder_views.xml',
        'views/product_views.xml',
        'views/menu_views.xml',
        'views/mrp_electronics_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            ('include', 'web.chartjs_lib'),
            'sn_wsd_mrp/static/src/scss/mrp_production.scss',
        ],
    },
    'installable': True,
    'application': False,
    'author': 'SNCIC',
    'license': 'LGPL-3',
}
